# Generated by Django 2.2.5 on 2020-02-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted_date',
            field=models.CharField(default='2, 1, 2020', max_length=20),
        ),
    ]
