# Generated by Django 2.2.5 on 2020-01-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('verified', models.NullBooleanField(default=False)),
                ('about_me', models.CharField(default='I have no life!', max_length=1000)),
                ('profile_pic', models.ImageField(default='profilepictures/default.jpg', upload_to='profilepictures')),
                ('level', models.IntegerField(default=1)),
                ('level_text', models.CharField(default='Citizen Scientist', max_length=50)),
                ('posts', models.IntegerField(default=0)),
                ('forum_signature', models.CharField(default='No Signature', max_length=100)),
                ('uuid', models.CharField(default='defaultforDB', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateScienceEntry',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=10000)),
                ('entry', models.IntegerField(primary_key=True, serialize=False)),
                ('posted_by', models.CharField(default='user', max_length=50)),
                ('posted_date', models.CharField(default='1, 18, 2020', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EcologyEntry',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=10000)),
                ('entry', models.IntegerField(primary_key=True, serialize=False)),
                ('posted_by', models.CharField(default='user', max_length=50)),
                ('posted_date', models.CharField(default='1, 18, 2020', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalScienceEntry',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=10000)),
                ('entry', models.IntegerField(primary_key=True, serialize=False)),
                ('posted_by', models.CharField(default='user', max_length=50)),
                ('posted_date', models.CharField(default='1, 18, 2020', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyEntry',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=10000)),
                ('entry', models.IntegerField(primary_key=True, serialize=False)),
                ('posted_by', models.CharField(default='user', max_length=50)),
                ('posted_date', models.CharField(default='1, 18, 2020', max_length=20)),
            ],
        ),
    ]
